// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzBzfB1m7SpASWDM8_BO6VbqM3HweEUzA',
    appId: '1:678773207399:web:9ca7b18e4f834f7bd9bfc2',
    messagingSenderId: '678773207399',
    projectId: 'quickensole',
    authDomain: 'quickensole.firebaseapp.com',
    storageBucket: 'quickensole.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4B2VuXra1IEWJEVYr29cwmCM6RobEcL8',
    appId: '1:678773207399:android:43dd88851ad1fd48d9bfc2',
    messagingSenderId: '678773207399',
    projectId: 'quickensole',
    storageBucket: 'quickensole.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDukyaqztYtCFzAsX1yBwaWjVoMw9RAstg',
    appId: '1:678773207399:ios:f7e133e34f75c03cd9bfc2',
    messagingSenderId: '678773207399',
    projectId: 'quickensole',
    storageBucket: 'quickensole.appspot.com',
    iosBundleId: 'com.example.quicknsoleAssesment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDukyaqztYtCFzAsX1yBwaWjVoMw9RAstg',
    appId: '1:678773207399:ios:f7e133e34f75c03cd9bfc2',
    messagingSenderId: '678773207399',
    projectId: 'quickensole',
    storageBucket: 'quickensole.appspot.com',
    iosBundleId: 'com.example.quicknsoleAssesment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzBzfB1m7SpASWDM8_BO6VbqM3HweEUzA',
    appId: '1:678773207399:web:b3dfee00a5bc78d1d9bfc2',
    messagingSenderId: '678773207399',
    projectId: 'quickensole',
    authDomain: 'quickensole.firebaseapp.com',
    storageBucket: 'quickensole.appspot.com',
  );
}
